CREATE DATABASE workshop;
CREATE ROLE workshop WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'workshop';
GRANT ALL PRIVILEGES ON DATABASE workshop TO workshop;